import { useState, useEffect } from "react";
import Head from "next/head";
import Job from "../components/Job";
import JobCardLoader from "../components/JobCardLoader";
import PrimaryButton from "../components/PrimaryButton";
import PrimaryButtonLoading from "../components/PrimaryButtonLoading";

export default function Home() {
  const [currentPage, setPage] = useState(1);
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      const res = await fetch(
        `https://api.adzuna.com/v1/api/jobs/gb/search/${currentPage}?app_id=8cd24105&app_key=4d7672bce24eeed99eb17ac3cda79387&results_per_page=20&sort_by=date`
      );
      const newData = await res.json();
      if (newData.results) {
        setData([...data, ...newData.results]);
        setLoading(false);
      }
    };

    fetchData();
    console.log()
  }, [currentPage]);



  const loadNewData = () => {
    setPage(currentPage + 1);
  };

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex relative min-h-full items-center justify-center py-12 px-4">
          <div className="w-full">

            {/* Sceleton loader */}
            {!data[0] && Array.from({ length: 12 })
              .map((_, index) => (
                <JobCardLoader key={index} />
              )
              )}

            {/* Job card list */}
            <ul className="flex flex-col space-y-6">
              {data.map((result) => {
                const { id, title, company, location, contract_time, created } =
                  result;
                const { display_name: company_name } = company;
                const { display_name: location_name } = location;

                return (
                  <li key={id}>
                    <Job
                      company_name={company_name}
                      location_name={location_name}
                      title={title}
                      created={created}
                      contract_time={
                        contract_time === "full_time"
                          ? "Full-time"
                          : "Part-time"
                      }
                    />
                  </li>
                );
              })}
            </ul>
            {/* Load more job cards */}
            <div className="h-60 absolute inset-x-0 bottom-0 bg-gradient-to-t from-white dark:from-gray-900"></div>
            <div className="h-60 absolute inset-x-0 bottom-0 bg-gradient-to-t from-white dark:from-gray-900"></div>
            <div className="h-60 absolute inset-x-0 bottom-0 bg-gradient-to-t from-white dark:from-gray-900"></div>

            <div className="absolute z-10 bottom-14 right-1/2 translate-x-1/2">
              {loading ? <PrimaryButtonLoading /> : <PrimaryButton onClick={loadNewData} text="Show More" />}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
